apiVersion: v1
kind: Namespace
metadata:
  name: operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql
  namespace: operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: full
  namespace: operator
rules:
  # Права на кастомные ресурсы CRD mysqls
  - apiGroups: ["otus.homework"]
    resources: ["mysqls", "mysqls/status"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Права на Service
  - apiGroups: [""]
    resources: ["services","persistentvolumes","persistentvolumeclaims"]
    verbs: ["create", "delete", "get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: BindingFull
  namespace: operator
subjects:
  - kind: ServiceAccount
    name: mysql
    namespace: operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: full
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mysqls.otus.homework
spec:
  scope: Namespaced
  group: otus.homework
  names:
    plural: mysqls
    kind: MySQL
    shortNames: 
      - mysql
    singular: mysql
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                database:
                  type: string
                password:
                  type: string
                storage_size:
                  type: string
            status:
              type: object
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-operator
  template:
    metadata:
      labels:
        app: mysql-operator
    spec:
      serviceAccountName: mysql
      containers:
      - name: mysql-operator
        image: roflmaoinmysoul/mysql-operator:1.0.0
        imagePullPolicy: IfNotPresent
---
apiVersion: otus.homework/v1
kind: MySQL
metadata:
  name: mysql-example
  namespace: operator
spec:
  image: "mysql:lts"
  database: "cordon"
  password: "3e!9)(j01n7O"
  storage_size: "1G"
