apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ index .Values "role-admin" "name" }}
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: [""]  
    resources: [""]  
    verbs: ["*"]
