apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim
  namespace: homework
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: custom-class
  resources:
    requests:
      storage: 1Gi